name: bukara
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  velocity_x: 3.5.1
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  unicons: any
  fluent_ui: 3.12.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  country_pickers: ^2.0.0
  iconsax: ^0.0.8
  cached_network_image: ^3.2.3
  file_picker: ^5.2.4
  table_calendar: ^3.0.8
  shimmer_animation: ^2.1.0+1
  printing: ^5.9.3
  pdf: ^3.8.4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  
  assets: 
    - assets/svg/
    - assets/icons/
    - assets/images/
fonts: 
    - family: Futura
      fonts: 
        - asset: assets/fonts/Futura/Futura-Maxi-CG Bold-Regular.otf
    - family: Comfortaa
      fonts: 
        - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
    - family: GoogleSans
      fonts: 
        - asset: assets/fonts/GoogleSans/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-BoldItalic.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-Italic.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-MediumItalic.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-Regular.ttf
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
